### PR TITLE
Add Mail destination for Alerting

### PR DESCRIPTION
**Pull request by dchauviere**
*Description of changes:*

Add UI for using Mail destination

see details in opendistro-for-elasticsearch/alerting#102

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by lvndc** [comment]
@dchauviere Thank you for raising this PR (Add Mail destination: [102](https://github.com/opendistro-for-elasticsearch/alerting/pull/102) and [91](https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/pull/91)). We’re in the process of reviewing this PR. However, before we can merge this PR, I have a list of suggested changes based on security, design and UX best practices that we use for Open Distro. Please track comments on this PR. Look forward to working together on this change.

**Comment by servergeeks** [comment]
Waiting also for this PR.....

**Comment by bjolivot** [comment]
Any news on review ?

**Comment by HimuraKenshin240** [comment]
Hello, I tried to change the Files in order to add the e-mail and after i try to add a Destination as email i got an error:
[illegal_state_exception] Type should be one of the [chime, slack, custom_webhook, test_action]'
did someone have the same problem?

Thanks in advance.

**Comment by dchauviere** [comment]
@lvndc @stevensideyliu unit tests fail but it seems not related to my changes !

**Comment by qreshi** [comment]
Closing and continuing in #176

**Pull request closed without merging**
