### PR TITLE
Allow longer FQDN and IPv4/v6 in host field

### PR DESCRIPTION
**Pull request by srilumpa**
This PR should fix the following issues :

* issue #14 
* issue #103 
* issue #127 

It is complementary to the PR #115 since it fixed the domain name only for the full URL field and not also for the standalone domain field.

For better code reuse, I moved the various regexes from the `validateURL` method out of it in order to mutualize them with the `validateHost` method. That way, the same regexes are used to validate both the standalone _Host_ field and the hostname/ip in the full URL field.

Entering hostname, IPv4 or IPv6 is now valid in the standalone _Host_ field.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by youtous** [comment]
Thank you for fixing this!

Is your validation working with simple hostname such as a [docker service name](https://docs.docker.com/compose/networking/) (using for inter container communication) ?

I'm using a webhook processor in a container, I would like to be able to query the webhook service using it's name: `http://webhook:8080/email` or with `http://webhook/email`.

**Comment by H1L021** [comment]
Still having this issue with plugin 1.7.0 :
image

**Comment by srilumpa** [comment]
Hi @youtous, no it won't work since the applied regexp to validate hostname keeps looking for a full FQDN.

**Comment by youtous** [comment]
Hi @srilumpa, 

Could you make it work for simples domains? 
I'm pretty sure it could be useful for docker setup where services are queried by their name (in docker swarm you can't define static ip, so unless adding a startup script for updating `/etc/hosts` in the container, consequently we are unable to set a service url in this field).

The current workaround I use is:
```
POST _opendistro/_alerting/destinations
{
  "name": "smtp",
  "type": "custom_webhook",
  "custom_webhook": {
    "url": "http://alerts-smtp-forwarder:8080/email"
  }
}
```
But it's not GUI friendly, thank you :)

**Comment by srilumpa** [comment]
I understand the issue but this would mean the validation to be much more permissive and I am not at the right place to take that design decision. If I have a go from @dbbaughe or other people from the Opendistro team, I can adapt the validation to allow short names to be set in through the GUI.

**Comment by dbbaughe** [comment]
Hey @srilumpa, thanks for the PR.

For @youtous case, does the example already work just through the API layer (instead of Kibana)? If so it should be perfectly fine to allow it. If it doesn't then it would need to be handled also on the backend plugin too. This Kibana plugin is just a frontend layer to the Elasticsearch plugin. All the real validation will be happening there, whereas here it's just to help the user make correct choices that are known not to fail. It seems the current validation has been too restrictive though if all of this is already allowed by backend plugin.

**Comment by srilumpa** [comment]
Thank you for your feedback. I will fix something less restrictive

**Comment by srilumpa** [comment]
I think this last commit should do the trick

**Review by skkosuri-amzn — APPROVED** [review]

**Comment by skkosuri-amzn** [comment]
@srilumpa  Apologies for the delay on this. Thanks for this PR. Tested this on 1.13 release. Targeted for next OpenDistro release.

**Comment by skkosuri-amzn** [comment]
On backend, we added ["Support host deny list for Destinations" ](https://github.com/opendistro-for-elasticsearch/alerting/pull/353). Made sure that is IPv6 supported.

**Review by tlfeng — APPROVED** [review]

**Pull request merged**
