### PR TITLE
Adds support for Kibana 7.8.0

### PR DESCRIPTION
**Pull request by ftianli-amzn**
*Issue #, if available:*
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/162

*Description of changes:*
- Update the plugin version to 1.9.0.0 in `package.json`
- Update Kibana version to 7.8.0 in `package.json`
- Update node version to 10.21.0 in `package.json`
- Update the Release Notes
- Move the plugin entry into Kibana app category in sidebar (reference: https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/pull/241)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ftianli-amzn** [comment]
```
Test Suites: 6 skipped, 78 passed, 78 of 84 total
Tests:       20 skipped, 366 passed, 386 total
Snapshots:   127 passed, 127 total
Time:        33.086s
Ran all test suites.
✨  Done in 34.22s.

**Comment by dbbaughe** [comment]
Hold off on merging until you verify compatibility with backend plugin and do one manual visual regression inspection

**Comment by ftianli-amzn** [comment]
> Hold off on merging until you verify compatibility with backend plugin and do one manual visual regression inspection

Ok, I will do a roughly manual regression test. Thank you!

**Comment by ftianli-amzn** [comment]
A screenshot of the current sidebar:
image

**Comment by ftianli-amzn** [comment]
Have tested the basic function with Alerting plugin 1.9.0.0

**Pull request merged**
